{
 "title": "PAC Backend",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request rate",
   "type": "graph",
   "description": "The amount of PAC Backend API request that was successfully handled in the last unit of time.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "RPS" }
   ],
   "targets": [
    {
     "expr": "rate(pac_backend_api_api_requests_total{job=\"pac-backend\",status=\"success\"}[1m])"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "description": "Percentage PAC Backend API request that resulted in errors in the last unit of time.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "RPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pac_backend_api_api_requests_total{job=\"pac-backend\",status=\"error\"}[1m])) / sum(rate(pac_backend_api_api_requests_total{job=\"pac-backend\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "graph",
   "description": "Latency  PAC Backend API requests.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "pac_backend_api_api_requests_summary{job=\"pac-backend\",service=\"duration\",quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "pac_backend_api_api_requests_summary{job=\"pac-backend\",service=\"duration\",quantile=\"0.9\"}",
     "legendFormat": "p90"
    },
    {
     "expr": "pac_backend_api_api_requests_summary{job=\"pac-backend\",service=\"duration\",quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}